baseURL = "https://www.robertvanbregt.nl/"
languageCode = "nl-NL"
defaultContentLanguage = "nl"
title = "Robert van Bregt"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Robert van Bregt"

[params]

    # Replace default "Hello" greeting
    greeting = "👋 Hallo!"

    [params.colors]
        background = "#4C566A"      # default = "#6fcdbd"
        foreground = "#ECEFF4"      # default = "#ffffff"
        hover      = "#BF616A"      # default = "#333333"

    [[params.links]]
        icon = "mastodon"
        title = "Mastodon"
        url = "https://mastodon.nl/@ro"

    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://linkedin.com/in/robertvanbregt"

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:q9cb2zo6@robertvanbregt.nl?subject=Contact%20via%20website&body=Hallo Robert,"
